package vn.ecohome.pos0210
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import java.text.SimpleDateFormat
import java.util.*
val Cream=Color(0xFFF7F2E9);val Ink=Color(0xFF211B18);val Coffee=Color(0xFF5A3C2D)
fun money(v:Int)="%,dđ".format(v).replace(',','.');fun clock(t:Long)=SimpleDateFormat("HH:mm",Locale.getDefault()).format(Date(t))
data class Dish(val name:String,val price:Int,val cat:String);data class PosTable(val id:Int,var name:String,var area:String);data class Batch(val no:Int,val orderItems:Map<String,Int>,val staff:String,val sentAt:Long=System.currentTimeMillis(),var printState:String="Đã gửi bếp");data class Session(val table:String,val area:String,val openedAt:Long=System.currentTimeMillis(),val batches:MutableList<Batch> = mutableListOf());data class Sale(val bill:String,val table:String,val area:String,val openedAt:Long,val closedAt:Long,val batches:List<Batch>,val total:Int,val method:String,val cashier:String)
class MainActivity:ComponentActivity(){override fun onCreate(b:Bundle?){super.onCreate(b);setContent{Pos()}}}
@Composable fun Pos(){val menu=remember{listOf(Dish("Đen đá",25000,"Cà phê"),Dish("Nâu đá",30000,"Cà phê"),Dish("Bạc xỉu",30000,"Cà phê"),Dish("Bún gà",40000,"Ăn sáng"),Dish("Đùi gà",55000,"Ăn sáng"),Dish("Cánh gà",45000,"Ăn sáng"),Dish("Trà mạn",25000,"Trà"),Dish("Trà đào",35000,"Trà"),Dish("Trà chanh",30000,"Trà"))};val tables=remember{mutableStateListOf(PosTable(1,"Bàn 01","Trong nhà"),PosTable(2,"Bàn 02","Trong nhà"),PosTable(3,"Bàn 03","Trong nhà"),PosTable(4,"Bàn 04","Trong nhà"),PosTable(5,"Bàn 05","Trong nhà"),PosTable(6,"Bàn 06","Trong nhà"),PosTable(7,"Bàn 07","Ngoài trời"),PosTable(8,"Bàn 08","Ngoài trời"))};val sessions=remember{mutableStateMapOf<String,Session>()};val sales=remember{mutableStateListOf<Sale>()};val cart=remember{mutableStateMapOf<String,Int>()};var screen by remember{mutableStateOf("TABLES")};var current by remember{mutableStateOf<PosTable?>(null)};var orderStaff by remember{mutableStateOf("Tuấn")};var cashier by remember{mutableStateOf("Tuấn")};fun sessionTotal(s:Session?):Int=s?.batches?.sumOf{b->b.orderItems.entries.sumOf{e->(menu.firstOrNull{it.name==e.key}?.price?:0)*e.value}}?:0;MaterialTheme(colorScheme=lightColorScheme(primary=Coffee,background=Cream,surface=Color(0xFFFFFCF7),onSurface=Ink)){Surface(Modifier.fillMaxSize(),color=Cream){when(screen){"TABLES"->Tables(tables,sessions,{p->current=p;sessions.getOrPut(p.name){Session(p.name,p.area)};cart.clear();screen="ORDER"},{screen="HISTORY"},{screen="REPORT"}){area->val n=tables.size+1;tables.add(PosTable(n,"Bàn %02d".format(n),area))};"ORDER"->Order(current!!,menu,cart,orderStaff,{orderStaff=it},{screen="TABLES"}){if(cart.isNotEmpty()){val s=sessions[current!!.name]!!;s.batches.add(Batch(s.batches.size+1,cart.toMap(),orderStaff));cart.clear();screen="SENT"}};"SENT"->Sent(current!!,sessions[current!!.name]!!,{screen="ORDER"},{screen="PAY"},{screen="TABLES"});"PAY"->Pay(current!!,sessions[current!!.name]!!,menu,cashier,{cashier=it},{screen="SENT"}){method->val s=sessions[current!!.name]!!;val now=System.currentTimeMillis();sales.add(Sale("0210-%04d".format(sales.size+1),s.table,s.area,s.openedAt,now,s.batches.toList(),sessionTotal(s),method,cashier));sessions.remove(current!!.name);cart.clear();screen="TABLES"};"HISTORY"->History(sales){screen="TABLES"};"REPORT"->Report(sales){screen="TABLES"}}}}}}
@Composable fun Brand(title:String="",back:(()->Unit)?=null){Row(Modifier.fillMaxWidth().padding(18.dp),verticalAlignment=Alignment.CenterVertically){if(back==null)Column{Text("0210",fontSize=30.sp,fontWeight=FontWeight.Black);Text("BREAKFAST · COFFEE · DRINKS",fontSize=9.sp)}else Text("‹",Modifier.clickable{back()}.padding(8.dp),fontSize=34.sp);Spacer(Modifier.weight(1f));Text(title,fontSize=22.sp,fontWeight=FontWeight.Bold)}}
@Composable fun Tables(tables:MutableList<PosTable>,sessions:Map<String,Session>,open:(PosTable)->Unit,history:()->Unit,report:()->Unit,add:(String)->Unit){var area by remember{mutableStateOf("Trong nhà")};Column{Brand();Row(Modifier.padding(horizontal=16.dp)){listOf("BÁN HÀNG","LỊCH SỬ","BÁO CÁO").forEach{x->Text(x,Modifier.weight(1f).clickable{if(x=="LỊCH SỬ")history() else if(x=="BÁO CÁO")report()}.padding(12.dp),fontWeight=if(x=="BÁN HÀNG")FontWeight.Bold else FontWeight.Normal)}};Row(Modifier.padding(16.dp)){FilterChip(area=="Trong nhà",{area="Trong nhà"},{Text("TRONG NHÀ")});Spacer(Modifier.width(8.dp));FilterChip(area=="Ngoài trời",{area="Ngoài trời"},{Text("NGOÀI TRỜI")})};LazyColumn(Modifier.weight(1f).padding(horizontal=14.dp)){items(tables.filter{it.area==area}.chunked(2)){rowTables->Row{rowTables.forEach{t->val s=sessions[t.name];Card(Modifier.weight(1f).padding(5.dp).height(112.dp).clickable{open(t)},shape=RoundedCornerShape(12.dp)){Column(Modifier.fillMaxSize().padding(12.dp),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.Center){Text(t.name,fontWeight=FontWeight.Bold);if(s==null)Text("Trống",color=Coffee)else{Text("Đang phục vụ",fontSize=12.sp);Text(clock(s.openedAt),fontSize=11.sp)}}}}}}};Row(Modifier.padding(16.dp)){OutlinedButton({add(area)},Modifier.weight(1f)){Text("＋ TẠO BÀN")};Spacer(Modifier.width(8.dp));Button({open(PosTable(-1,"Mang đi","Mang đi"))},Modifier.weight(1f)){Text("MANG ĐI")}}}}
@Composable fun StaffPick(label:String,value:String,set:(String)->Unit){var expanded by remember{mutableStateOf(false)};Box{OutlinedButton({expanded=true}){Text("$label: $value ▾")};DropdownMenu(expanded,{expanded=false}){listOf("Tuấn","Hương","Nam").forEach{staffName->DropdownMenuItem(text={Text(staffName)},onClick={set(staffName);expanded=false})}}}}
@Composable fun Order(t:PosTable,menu:List<Dish>,cart:MutableMap<String,Int>,staff:String,setStaff:(String)->Unit,back:()->Unit,send:()->Unit){var cat by remember{mutableStateOf("Cà phê")};Column{Brand(t.name,back);Row(Modifier.padding(horizontal=12.dp)){listOf("Cà phê","Ăn sáng","Trà").forEach{x->FilterChip(cat==x,{cat=x},{Text(x)},Modifier.padding(3.dp))}};Box(Modifier.padding(horizontal=16.dp)){StaffPick("NV order",staff,setStaff)};LazyColumn(Modifier.weight(1f).padding(12.dp)){items(menu.filter{it.cat==cat}){d->val q=cart[d.name]?:0;Card(Modifier.fillMaxWidth().padding(4.dp)){Row(Modifier.padding(14.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(d.name,fontWeight=FontWeight.Bold);Text(money(d.price))};if(q>0){Text("−",Modifier.clickable{if(q==1)cart.remove(d.name)else cart[d.name]=q-1}.padding(12.dp));Text("$q")};Text("＋",Modifier.clickable{cart[d.name]=q+1}.padding(12.dp),fontWeight=FontWeight.Bold)}}}};Button(send,enabled=cart.isNotEmpty(),modifier=Modifier.fillMaxWidth().padding(16.dp).height(58.dp)){Text("GỬI LÀM HÀNG")}}}
@Composable fun Sent(t:PosTable,s:Session,more:()->Unit,pay:()->Unit,home:()->Unit){Column{Brand(t.name,home);Text("ĐÃ GỌI",Modifier.padding(horizontal=18.dp),fontSize=20.sp,fontWeight=FontWeight.Bold);LazyColumn(Modifier.weight(1f).padding(12.dp)){items(s.batches){b->Card(Modifier.fillMaxWidth().padding(5.dp)){Column(Modifier.padding(14.dp)){Row{Text("${clock(b.sentAt)} · Đơn #${b.no.toString().padStart(3,'0')}",fontWeight=FontWeight.Bold);Spacer(Modifier.weight(1f));Text("● ${b.printState}",color=Color(0xFF3F7D59),fontSize=12.sp)};Text("Order: ${b.staff}",fontSize=11.sp,color=Coffee);b.orderItems.forEach{(n,q)->Text("$q × $n",Modifier.padding(top=9.dp))}}}}};Row(Modifier.padding(16.dp)){OutlinedButton(more,Modifier.weight(1f)){Text("＋ GỌI THÊM")};Spacer(Modifier.width(8.dp));Button(pay,Modifier.weight(1f)){Text("XEM TẠM TÍNH")}}}}
@Composable fun Pay(t:PosTable,s:Session,menu:List<Dish>,cashier:String,setCashier:(String)->Unit,back:()->Unit,done:(String)->Unit){var method by remember{mutableStateOf("CASH")};val all=mutableMapOf<String,Int>();s.batches.forEach{b->b.orderItems.forEach{(n,q)->all[n]=(all[n]?:0)+q}};val total=all.entries.sumOf{e->(menu.first{it.name==e.key}.price)*e.value};Column{Brand("Thanh toán",back);Column(Modifier.weight(1f).padding(18.dp)){Text("${t.name} · ${t.area}",fontWeight=FontWeight.Bold);Text("Mở bàn ${clock(s.openedAt)}",fontSize=12.sp,color=Coffee);all.forEach{(n,q)->Row(Modifier.padding(vertical=7.dp)){Text("$q × $n");Spacer(Modifier.weight(1f));Text(money(menu.first{it.name==n}.price*q))}};HorizontalDivider();Row(Modifier.padding(vertical=16.dp)){Text("Tổng cộng",fontWeight=FontWeight.Bold);Spacer(Modifier.weight(1f));Text(money(total),fontSize=25.sp,fontWeight=FontWeight.Black)};Row{FilterChip(method=="CASH",{method="CASH"},{Text("Tiền mặt")});Spacer(Modifier.width(8.dp));FilterChip(method=="TRANSFER",{method="TRANSFER"},{Text("Chuyển khoản")})};Spacer(Modifier.height(14.dp));StaffPick("Người thu tiền",cashier,setCashier)};Button({done(method)},Modifier.fillMaxWidth().padding(18.dp).height(60.dp)){Text("✓ XÁC NHẬN THANH TOÁN")}}}
@Composable fun History(sales:List<Sale>,back:()->Unit){Column{Brand("Lịch sử",back);if(sales.isEmpty())Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){Text("Chưa có bill đã thanh toán")}else LazyColumn(Modifier.padding(14.dp)){items(sales.reversed()){sale->Card(Modifier.fillMaxWidth().padding(5.dp)){Column(Modifier.padding(14.dp)){Row{Text(sale.bill,fontWeight=FontWeight.Bold);Spacer(Modifier.weight(1f));Text(money(sale.total),fontWeight=FontWeight.Bold)};Text("${sale.table} · ${sale.area} · ${clock(sale.openedAt)}–${clock(sale.closedAt)}");Text("Thu tiền: ${sale.cashier} · ${if(sale.method=="CASH")"Tiền mặt" else "Chuyển khoản"}",fontSize=12.sp);sale.batches.forEach{b->Text("Đơn #${b.no}: ${b.staff} · ${b.orderItems.entries.joinToString{"${it.value}×${it.key}"}}",fontSize=11.sp,color=Coffee)}}}}}}}
@Composable fun Report(sales:List<Sale>,back:()->Unit){val total=sales.sumOf{it.total};val cash=sales.filter{it.method=="CASH"}.sumOf{it.total};val itemCount=mutableMapOf<String,Int>();val hourly=mutableMapOf<Int,Int>();val byCashier=mutableMapOf<String,Int>();sales.forEach{sale->sale.batches.forEach{b->b.orderItems.forEach{(n,q)->itemCount[n]=(itemCount[n]?:0)+q}};val h=Calendar.getInstance().apply{timeInMillis=sale.closedAt}.get(Calendar.HOUR_OF_DAY);hourly[h]=(hourly[h]?:0)+sale.total;byCashier[sale.cashier]=(byCashier[sale.cashier]?:0)+sale.total};val peak=hourly.maxByOrNull{it.value};Column{Brand("Báo cáo",back);LazyColumn(Modifier.padding(16.dp)){item{Card(Modifier.fillMaxWidth()){Column(Modifier.fillMaxWidth().padding(20.dp),horizontalAlignment=Alignment.CenterHorizontally){Text("Tổng doanh thu");Text(money(total),fontSize=32.sp,fontWeight=FontWeight.Black);Text("${sales.size} bill · TB ${money(if(sales.isEmpty())0 else total/sales.size)}")}};Spacer(Modifier.height(10.dp));Row{Text("Tiền mặt: ${money(cash)}",Modifier.weight(1f));Text("Chuyển khoản: ${money(total-cash)}")};Spacer(Modifier.height(18.dp));Text("GIỜ CAO ĐIỂM",fontWeight=FontWeight.Bold);Text(if(peak==null)"Chưa đủ dữ liệu" else "%02d:00–%02d:00 · %s".format(peak.key,peak.key+1,money(peak.value)));Spacer(Modifier.height(18.dp));Text("MÓN BÁN CHẠY",fontWeight=FontWeight.Bold)};items(itemCount.entries.sortedByDescending{it.value}.take(5)){entry->Row(Modifier.padding(vertical=6.dp)){Text(entry.key);Spacer(Modifier.weight(1f));Text("${entry.value}")}};item{Spacer(Modifier.height(18.dp));Text("ĐỐI SOÁT NGƯỜI THU TIỀN",fontWeight=FontWeight.Bold)};items(byCashier.entries.toList()){entry->Row(Modifier.padding(vertical=6.dp)){Text(entry.key);Spacer(Modifier.weight(1f));Text(money(entry.value),fontWeight=FontWeight.Bold)}}}}}
