package vn.ecohome.pos0210

import android.net.Uri
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.BackHandler
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.compose.setContent
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

val Cream=Color(0xFFF4EFE7); val Ink=Color(0xFF2C211B); val Coffee=Color(0xFF5A4032)
data class Dish(val name:String,var price:Int,var cat:String,var enabled:Boolean=true,var imageUri:String?=null)
fun money(v:Int)="%,dđ".format(v).replace(',', '.')
class MainActivity:ComponentActivity(){override fun onCreate(b:Bundle?){super.onCreate(b);setContent{Pos()}}}
@Composable fun Pos(){var screen by remember{mutableStateOf("TABLES")};var table by remember{mutableStateOf("Bàn 01")};val menu=remember{mutableStateListOf(Dish("Bún gà",40000,"Ăn sáng"),Dish("Bún gà đùi",55000,"Ăn sáng"),Dish("Cà phê đen",25000,"Cà phê"),Dish("Cà phê sữa",30000,"Cà phê"),Dish("Trà đào",35000,"Trà"),Dish("Sinh tố xoài",40000,"Sinh tố"))};val cart=remember{mutableStateMapOf<String,Int>()};fun home(){screen="TABLES"};BackHandler(screen!="TABLES"){screen=when(screen){"ORDER"->"TABLES";"SENT"->"ORDER";"PAY"->"SENT";"MENU_ADD"->"MENU";else->"TABLES"}};MaterialTheme(colorScheme=lightColorScheme(primary=Coffee,background=Cream,surface=Color(0xFFFFFCF7),onSurface=Ink)){Surface(Modifier.fillMaxSize(),color=Cream){Box(Modifier.fillMaxSize().windowInsetsPadding(WindowInsets.safeDrawing)){when(screen){"TABLES"->Tables({table=it;screen="ORDER"},{screen="MENU"});"ORDER"->Order(table,menu,cart,{screen="TABLES"},{screen="TABLES"},{screen="SENT"});"SENT"->Sent(table,{screen="ORDER"},{screen="PAY"},{screen="TABLES"});"PAY"->Pay(table,{screen="SENT"},{home()});"MENU"->MenuManager(menu,{screen="TABLES"},{screen="MENU_ADD"});"MENU_ADD"->AddDish(menu,{screen="MENU"})}}}}}
@Composable fun Top(title:String,sub:String,onBack:(()->Unit)?=null,onHome:(()->Unit)?=null){Row(Modifier.fillMaxWidth().padding(horizontal=18.dp,vertical=12.dp),verticalAlignment=Alignment.CenterVertically){if(onBack!=null)TextButton(onBack){Text("‹ BACK",fontWeight=FontWeight.Bold)}else Text("0210",fontSize=27.sp,fontWeight=FontWeight.Black);Spacer(Modifier.weight(1f));Column(horizontalAlignment=Alignment.End){Text(title,fontWeight=FontWeight.Bold);Text(sub,fontSize=12.sp,color=Coffee)};if(onHome!=null)TextButton(onHome){Text("⌂",fontSize=24.sp)}}}
@Composable fun Tables(open:(String)->Unit,menu:()->Unit){Column{Top("BÁN HÀNG","Chọn bàn");Row(Modifier.padding(horizontal=18.dp),verticalAlignment=Alignment.CenterVertically){Text("TRONG NHÀ",fontWeight=FontWeight.Bold);Spacer(Modifier.weight(1f));TextButton(menu){Text("QUẢN LÝ MENU")}};LazyColumn(Modifier.weight(1f).padding(horizontal=14.dp)){items((1..8).map{"Bàn %02d".format(it)}){x->Card(Modifier.fillMaxWidth().padding(5.dp).clickable{open(x)},shape=RoundedCornerShape(18.dp)){Row(Modifier.padding(20.dp)){Text(x,fontWeight=FontWeight.Bold);Spacer(Modifier.weight(1f));Text("TRỐNG",fontSize=12.sp,color=Coffee)}}}};Button({open("Mang đi")},Modifier.fillMaxWidth().padding(18.dp).height(54.dp)){Text("MANG ĐI")}}}
@Composable fun Order(t:String,menu:List<Dish>,cart:MutableMap<String,Int>,back:()->Unit,home:()->Unit,send:()->Unit){var cat by remember{mutableStateOf("Tất cả")};val cats=listOf("Tất cả","Cà phê","Ăn sáng","Trà","Sinh tố","Khác");val count=cart.values.sum();val total=menu.sumOf{it.price*(cart[it.name]?:0)};Column{Top(t,"ORDER MÓN",back,home);Row(Modifier.fillMaxWidth().padding(horizontal=8.dp),horizontalArrangement=Arrangement.SpaceEvenly){cats.take(5).forEach{Text(it,Modifier.clickable{cat=it}.padding(6.dp),fontSize=13.sp,fontWeight=if(cat==it)FontWeight.Black else FontWeight.Normal)}};LazyColumn(Modifier.weight(1f).padding(12.dp)){items(menu.filter{it.enabled&&(cat=="Tất cả"||it.cat==cat)}){d->val q=cart[d.name]?:0;Card(Modifier.fillMaxWidth().padding(5.dp),shape=RoundedCornerShape(18.dp)){Row(Modifier.fillMaxWidth().padding(14.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(54.dp).background(Color(0xFFE5DDD7),RoundedCornerShape(12.dp)),contentAlignment=Alignment.Center){Text(if(d.imageUri==null)"ẢNH" else "✓",fontSize=11.sp,color=Coffee)};Spacer(Modifier.width(12.dp));Column(Modifier.weight(1f)){Text(d.name,fontWeight=FontWeight.Bold);Text(money(d.price),color=Coffee)};if(q>0){OutlinedButton({if(q<=1)cart.remove(d.name)else cart[d.name]=q-1},contentPadding=PaddingValues(0.dp),modifier=Modifier.size(40.dp)){Text("−")};Text("$q",Modifier.width(30.dp),fontWeight=FontWeight.Black);OutlinedButton({cart[d.name]=q+1},contentPadding=PaddingValues(0.dp),modifier=Modifier.size(40.dp)){Text("+")}}else Button({cart[d.name]=1}){Text("+")}}}}};Row(Modifier.fillMaxWidth().padding(horizontal=18.dp),verticalAlignment=Alignment.CenterVertically){Text("$count món • ${money(total)}",fontWeight=FontWeight.Black);Spacer(Modifier.weight(1f));TextButton({}){Text("XEM GIỎ")}};Button(send,enabled=count>0,modifier=Modifier.fillMaxWidth().padding(18.dp).height(56.dp)){Text("GỬI LÀM HÀNG",fontWeight=FontWeight.Bold)}}}
@Composable fun Sent(t:String,more:()->Unit,pay:()->Unit,home:()->Unit){Column{Top(t,"ĐÃ GỌI",more,home);Card(Modifier.fillMaxWidth().padding(18.dp)){Column(Modifier.padding(20.dp)){Text("ĐƠN VỪA GỬI",fontWeight=FontWeight.Black);Text("Chờ in Bluetooth",color=Coffee)}};Spacer(Modifier.weight(1f));Row(Modifier.padding(18.dp)){OutlinedButton(more,Modifier.weight(1f)){Text("GỌI THÊM")};Spacer(Modifier.width(8.dp));Button(pay,Modifier.weight(1f)){Text("THANH TOÁN")}}}}
@Composable fun Pay(t:String,back:()->Unit,done:()->Unit){var method by remember{mutableStateOf("TRANSFER")};Column{Top(t,"THANH TOÁN",back,done);Column(Modifier.weight(1f).padding(22.dp)){Text("TỔNG CỘNG",color=Coffee);Text("135.000đ",fontSize=32.sp,fontWeight=FontWeight.Black);Spacer(Modifier.height(20.dp));Row{FilterChip(method=="CASH",{method="CASH"},{Text("TIỀN MẶT")});Spacer(Modifier.width(10.dp));FilterChip(method=="TRANSFER",{method="TRANSFER"},{Text("CHUYỂN KHOẢN")})};if(method=="TRANSFER")Card(Modifier.fillMaxWidth().padding(top=18.dp)){Column(Modifier.fillMaxWidth().padding(24.dp),horizontalAlignment=Alignment.CenterHorizontally){Text("CHƯA CẤU HÌNH VIETQR",fontWeight=FontWeight.Black);Text("Cần nhập ngân hàng, số tài khoản và chủ tài khoản trong Cài đặt.",Modifier.padding(top=8.dp),fontSize=13.sp,color=Coffee)}}};Button(done,Modifier.fillMaxWidth().padding(18.dp).height(58.dp)){Text(if(method=="CASH")"XÁC NHẬN ĐÃ TRẢ TIỀN MẶT" else "XÁC NHẬN ĐÃ NHẬN CHUYỂN KHOẢN",fontWeight=FontWeight.Bold)}}}
@Composable fun MenuManager(menu:MutableList<Dish>,back:()->Unit,add:()->Unit){Column{Top("QUẢN LÝ MENU","V0.4",back,back);Button(add,Modifier.fillMaxWidth().padding(horizontal=18.dp,vertical=8.dp).height(52.dp)){Text("+ THÊM MÓN")};LazyColumn(Modifier.weight(1f).padding(14.dp)){items(menu){d->Card(Modifier.fillMaxWidth().padding(5.dp)){Row(Modifier.padding(14.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(48.dp).background(Color(0xFFE5DDD7),RoundedCornerShape(10.dp)),contentAlignment=Alignment.Center){Text(if(d.imageUri==null)"ẢNH" else "✓",fontSize=10.sp)};Spacer(Modifier.width(12.dp));Column(Modifier.weight(1f)){Text(d.name,fontWeight=FontWeight.Bold);Text("${d.cat} • ${money(d.price)}")};Switch(d.enabled,{d.enabled=it;val i=menu.indexOf(d);menu[i]=d})}}}}}}
@Composable fun AddDish(menu:MutableList<Dish>,back:()->Unit){var name by remember{mutableStateOf("")};var price by remember{mutableStateOf("")};var cat by remember{mutableStateOf("Cà phê")};var image by remember{mutableStateOf<Uri?>(null)};var expanded by remember{mutableStateOf(false)};val picker=rememberLauncherForActivityResult(ActivityResultContracts.GetContent()){image=it};Column{Top("THÊM MÓN","Menu",back,back);Column(Modifier.padding(20.dp)){OutlinedTextField(name,{name=it},label={Text("Tên món")},modifier=Modifier.fillMaxWidth());Spacer(Modifier.height(10.dp));OutlinedTextField(price,{price=it.filter(Char::isDigit)},label={Text("Giá bán")},modifier=Modifier.fillMaxWidth());Spacer(Modifier.height(10.dp));Box{OutlinedButton({expanded=true},Modifier.fillMaxWidth()){Text("PHÂN LOẠI: $cat")};DropdownMenu(expanded,{expanded=false}){listOf("Cà phê","Ăn sáng","Trà","Sinh tố","Khác").forEach{x->DropdownMenuItem({Text(x)},{cat=x;expanded=false})}}};Spacer(Modifier.height(10.dp));OutlinedButton({picker.launch("image/*")},Modifier.fillMaxWidth().height(54.dp)){Text(if(image==null)"CHỌN ẢNH ĐẠI DIỆN" else "✓ ĐÃ CHỌN ẢNH — ĐỔI ẢNH")};Spacer(Modifier.height(24.dp));Button({val p=price.toIntOrNull();if(name.isNotBlank()&&p!=null){menu.add(Dish(name,p,cat,true,image?.toString()));back()}},Modifier.fillMaxWidth().height(56.dp)){Text("LƯU MÓN",fontWeight=FontWeight.Bold)}}}}