package vn.ecohome.pos0210
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.lifecycle.viewmodel.compose.viewModel
import vn.ecohome.pos0210.data.*
import java.text.SimpleDateFormat
import java.util.*
private val Cream=Color(0xFFF7F2E9);private val Coffee=Color(0xFF65422F);private val Tint=Color(0xFFE9E2EA);private val Occupied=Color(0xFFE2C2A8)
private fun money(v:Long)="%,dđ".format(v).replace(',','.');private fun time(v:Long)=SimpleDateFormat("dd/MM HH:mm",Locale.getDefault()).format(Date(v))
class MainActivity:ComponentActivity(){override fun onCreate(b:Bundle?){super.onCreate(b);enableEdgeToEdge();setContent{MaterialTheme(colorScheme=lightColorScheme(primary=Coffee,background=Cream)){Surface(Modifier.fillMaxSize().safeDrawingPadding(),color=Cream){App()}}}}}
@Composable fun App(vm:PosViewModel=viewModel()){val sc by vm.screen.collectAsState();val t by vm.currentTable.collectAsState();val s by vm.currentSession.collectAsState();when(sc){"LOGIN"->Login(vm);"TABLES"->Tables(vm);"ORDER"->t?.let{Order(vm,it)};"SENT"->if(t!=null&&s!=null)Sent(vm,t!!,s!!);"PAY"->if(t!=null&&s!=null)Pay(vm,t!!,s!!);"REPORT"->Report(vm);"MANAGE"->Manage(vm);"EMP"->Employees(vm);"PURCHASE"->Purchases(vm);"VIETQR"->VietQr(vm);"PRINTER"->Printer(vm);"SETTINGS"->Settings(vm)}}
@Composable fun Header(title:String="",back:(()->Unit)?=null){Row(Modifier.fillMaxWidth().padding(18.dp),verticalAlignment=Alignment.CenterVertically){if(back==null)Column{Text("0210",fontSize=32.sp,fontWeight=FontWeight.Black);Text("BREAKFAST · COFFEE · DRINKS",fontSize=9.sp)}else Text("‹",Modifier.clickable{back()}.padding(6.dp),fontSize=36.sp);Spacer(Modifier.weight(1f));Text(title,fontSize=21.sp,fontWeight=FontWeight.Bold)}}
@Composable fun Login(vm:PosViewModel){var pin by remember{mutableStateOf("")};val err by vm.authError.collectAsState();Column(Modifier.fillMaxSize().padding(32.dp),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.Center){Text("0210",fontSize=48.sp,fontWeight=FontWeight.Black);Text("PIN NHÂN VIÊN",fontWeight=FontWeight.Bold);OutlinedTextField(pin,{pin=it.filter(Char::isDigit).take(4)},label={Text("PIN 4 số")},visualTransformation=PasswordVisualTransformation());if(err.isNotBlank())Text(err,color=MaterialTheme.colorScheme.error);Button({vm.login(pin)},Modifier.fillMaxWidth().padding(top=12.dp),enabled=pin.length==4){Text("ĐĂNG NHẬP")}}}
@Composable fun Operator(vm:PosViewModel){val e by vm.currentEmployee.collectAsState();AssistChip({vm.logout()},{Text("🔒 ${e?.name} · Đổi người")})}
@Composable fun Tables(vm:PosViewModel){val ts by vm.tables.collectAsState();val ss by vm.sessions.collectAsState();Column{Header();Operator(vm);LazyColumn(Modifier.weight(1f).padding(12.dp)){items(ts){tb->val open=ss.firstOrNull{it.tableId==tb.id};Card(Modifier.fillMaxWidth().height(92.dp).padding(5.dp).clickable{vm.selectTable(tb)},colors=CardDefaults.cardColors(containerColor=if(open==null)Tint else Occupied)){Column(Modifier.fillMaxSize(),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.Center){Text(tb.name,fontWeight=FontWeight.Bold);Text(if(open==null)"Trống" else "● ĐANG CÓ KHÁCH · ${time(open.openedAt)}")}}}};Row(Modifier.padding(12.dp)){Button({vm.screen.value="MANAGE"},Modifier.weight(1f)){Text("QUẢN LÝ")};Button({vm.screen.value="REPORT"},Modifier.weight(1f)){Text("BÁO CÁO")}}}}
@Composable fun Order(vm:PosViewModel,t:DiningTableEntity){val ms by vm.menu.collectAsState();val cart by vm.cart.collectAsState();Column{Header(t.name){vm.screen.value="TABLES"};LazyColumn(Modifier.weight(1f).padding(12.dp)){items(ms.filter{it.active}){m->val q=cart[m.id]?:0;Card(Modifier.fillMaxWidth().padding(4.dp)){Row(Modifier.padding(14.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(m.name,fontWeight=FontWeight.Bold);Text(money(m.price))};if(q>0)Text("− $q",Modifier.clickable{vm.sub(m)}.padding(10.dp));Text("＋",Modifier.clickable{vm.add(m)}.padding(10.dp))}}}};Button({vm.sendBatch()},Modifier.fillMaxWidth().padding(16.dp),enabled=cart.isNotEmpty()){Text("GỬI LÀM HÀNG")}}}
@Composable fun Sent(vm:PosViewModel,t:DiningTableEntity,s:TableSessionEntity){val bs by vm.batches(s.id).collectAsState(initial=emptyList());val total by vm.total(s.id).collectAsState(initial=0);var pv by remember{mutableStateOf<OrderBatchEntity?>(null)};Column{Header(t.name){vm.screen.value="TABLES"};LazyColumn(Modifier.weight(1f)){items(bs){b->Card(Modifier.fillMaxWidth().padding(8.dp).clickable{pv=b}){Column(Modifier.padding(14.dp)){Text("Đơn #${b.sequence}",fontWeight=FontWeight.Bold);Text(b.status)}}}};Text("Tạm tính ${money(total)}",Modifier.padding(16.dp));Button({vm.screen.value="PAY"},Modifier.fillMaxWidth().padding(16.dp)){Text("THANH TOÁN")}};pv?.let{b->val its by vm.items(b.id).collectAsState(initial=emptyList());AlertDialog(onDismissRequest={pv=null},confirmButton={Button(onClick={vm.markBatchSent(b);pv=null}){Text("XÁC NHẬN GỬI")}},dismissButton={TextButton(onClick={pv=null}){Text("ĐÓNG")}},title={Text("PREVIEW PHIẾU BẾP")},text={Column{Text("0210 · ${t.name}");its.forEach{Text("${it.qty} × ${it.itemNameSnapshot}")}}})}}
@Composable fun Pay(vm:PosViewModel,t:DiningTableEntity,s:TableSessionEntity){val total by vm.total(s.id).collectAsState(initial=0);val e by vm.currentEmployee.collectAsState();var method by remember{mutableStateOf("CASH")};Column{Header("Thanh toán"){vm.screen.value="SENT"};Column(Modifier.weight(1f).padding(18.dp)){Text("TỔNG CỘNG");Text(money(total),fontSize=38.sp,fontWeight=FontWeight.Black);Row{FilterChip(method=="CASH",{method="CASH"},{Text("TIỀN MẶT")});FilterChip(method=="TRANSFER",{method="TRANSFER"},{Text("CHUYỂN KHOẢN")})};Text("🔒 Thu tiền: ${e?.name}",Modifier.padding(vertical=14.dp));if(method=="TRANSFER")Card{Column(Modifier.padding(16.dp)){Text("VIETQR");Text("${vm.setting("bank_name")} · ${vm.setting("bank_account")}");Text("${money(total)} · ${vm.setting("qr_prefix").ifBlank{"0210"}} ${t.name}")}}};Button({vm.close(method,total)},Modifier.fillMaxWidth().padding(18.dp),enabled=total>0){Text("XÁC NHẬN THANH TOÁN")}}}
@Composable fun Manage(vm:PosViewModel){Column{Header("Quản lý"){vm.screen.value="TABLES"};Column(Modifier.padding(16.dp)){Rowx("Nhân viên","Thêm · khóa · phân quyền"){vm.screen.value="EMP"};Rowx("Nhập đầu vào","Ngày giờ thủ công"){vm.screen.value="PURCHASE"};Rowx("VietQR","Lưu tài khoản"){vm.screen.value="VIETQR"};Rowx("Máy in","Cấu hình"){vm.screen.value="PRINTER"};Rowx("Nhật ký","Audit"){vm.screen.value="SETTINGS"}}}}
@Composable fun Rowx(t:String,s:String,go:()->Unit){Card(Modifier.fillMaxWidth().padding(5.dp).clickable{go()}){Column(Modifier.padding(16.dp)){Text(t,fontWeight=FontWeight.Bold);Text(s,fontSize=12.sp)}}}
@Composable fun Employees(vm:PosViewModel){val es by vm.employees.collectAsState();Column{Header("Nhân viên"){vm.screen.value="MANAGE"};LazyColumn{items(es){e->Card(Modifier.fillMaxWidth().padding(6.dp)){Column(Modifier.padding(14.dp)){Text("${e.name} · ${e.role}",fontWeight=FontWeight.Bold);Text("Order ${e.canOrder} · Bếp ${e.canSendKitchen} · Thu ${e.canCheckout} · Nhập ${e.canPurchase}");Switch(e.active,{vm.toggleEmployee(e)})}}}}}}
@Composable fun Purchases(vm:PosViewModel){var n by remember{mutableStateOf("")};var a by remember{mutableStateOf("")};var dt by remember{mutableStateOf(SimpleDateFormat("dd/MM/yyyy HH:mm",Locale.getDefault()).format(Date()))};Column{Header("Nhập đầu vào"){vm.screen.value="MANAGE"};Column(Modifier.padding(16.dp)){OutlinedTextField(dt,{dt=it},label={Text("Ngày giờ dd/MM/yyyy HH:mm")});OutlinedTextField(n,{n=it},label={Text("Mặt hàng")});OutlinedTextField(a,{a=it.filter(Char::isDigit)},label={Text("Tổng tiền")});Button({val at=runCatching{SimpleDateFormat("dd/MM/yyyy HH:mm",Locale.getDefault()).parse(dt)?.time}.getOrNull()?:System.currentTimeMillis();vm.addPurchase(n,a.toLongOrNull()?:0,"",at)},enabled=n.isNotBlank()&&a.isNotBlank()){Text("TẠO PHIẾU")}}}}
@Composable fun VietQr(vm:PosViewModel){val sets by vm.settings.collectAsState();fun v(k:String)=sets.firstOrNull{it.key==k}?.value?:"";var bank by remember(sets){mutableStateOf(v("bank_name"))};var acc by remember(sets){mutableStateOf(v("bank_account"))};var holder by remember(sets){mutableStateOf(v("bank_holder"))};Column{Header("VietQR"){vm.screen.value="MANAGE"};Column(Modifier.padding(16.dp)){OutlinedTextField(bank,{bank=it},label={Text("Ngân hàng")});OutlinedTextField(acc,{acc=it},label={Text("Số tài khoản")});OutlinedTextField(holder,{holder=it},label={Text("Chủ tài khoản")});Button({vm.saveSetting("bank_name",bank);vm.saveSetting("bank_account",acc);vm.saveSetting("bank_holder",holder);vm.saveSetting("qr_prefix","0210")}){Text("LƯU")}}}}
@Composable fun Printer(vm:PosViewModel){Column{Header("Máy in"){vm.screen.value="MANAGE"};Text("Driver ESC/POS chưa kích hoạt",Modifier.padding(20.dp))}}
@Composable fun Report(vm:PosViewModel){val bs by vm.bills.collectAsState();Column{Header("Báo cáo"){vm.screen.value="TABLES"};Text("Doanh thu ${money(bs.sumOf{it.total})}",Modifier.padding(20.dp),fontSize=24.sp)}}
@Composable fun Settings(vm:PosViewModel){val a by vm.audits.collectAsState();Column{Header("Nhật ký"){vm.screen.value="MANAGE"};LazyColumn{items(a.take(30)){Text("${time(it.occurredAt)} · ${it.action}",Modifier.padding(8.dp))}}}}
